# Generated by Django 4.2.25 on 2025-11-11 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(help_text='URL of the tour image', max_length=500)),
                ('caption', models.CharField(blank=True, help_text='Optional image caption', max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Set as primary/featured image')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which images are displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tour_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tours.tourpackage')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
